In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('flood3.csv')

In [3]:
df.head()

,date,daily_avg_discharge,flood_event_runoff,daily_runoff,weekly_runoff,total_monthly_runoff,flood_magnitude
0,1-Jan-98,6440.0,NaN,0.61,4.27,23.4,0.0
1,2-Jan-98,6680.0,0.0,0.63,4.41,39.5,0.0
2,3-Jan-98,9234.0,0.0,0.87,6.09,31.2,0.0
3,4-Jan-98,8116.0,0.0,0.76,5.32,7.6,0.0
4,5-Jan-98,8230.0,0.0,0.77,5.39,19.7,0.0

In [4]:
import sklearn

In [5]:
df

,date,daily_avg_discharge,flood_event_runoff,daily_runoff,weekly_runoff,total_monthly_runoff,flood_magnitude
0,1-Jan-98,6440.0,NaN,0.61,4.27,23.4,0.0
1,2-Jan-98,6680.0,0.0,0.63,4.41,39.5,0.0
2,3-Jan-98,9234.0,0.0,0.87,6.09,31.2,0.0
3,4-Jan-98,8116.0,0.0,0.76,5.32,7.6,0.0
4,5-Jan-98,8230.0,0.0,0.77,5.39,19.7,0.0
...,...,...,...,...,...,...,...
9741,2-Sep-24,15529.0,0.0,1.46,8.20,NaN,0.0
9742,3-Sep-24,14566.0,0.0,1.37,8.76,NaN,0.0
9743,4-Sep-24,16110.0,0.0,1.52,9.40,NaN,0.0
9744,5-Sep-24,19168.0,0.0,1.80,10.05,NaN,0.0
9745,6-Sep-24,17030.0,0.0,1.60,10.45,NaN,0.0

In [6]:
df.isnull().sum()

date                       0
daily_avg_discharge       38
flood_event_runoff         1
daily_runoff               0
weekly_runoff              0
total_monthly_runoff    9422
flood_magnitude            0
dtype: int64

In [7]:
df['daily_avg_discharge'].mean()

10276.087453646478

In [8]:
df['daily_avg_discharge']= df['daily_avg_discharge'].fillna(10276)

In [9]:
df.isnull().sum()

date                       0
daily_avg_discharge        0
flood_event_runoff         1
daily_runoff               0
weekly_runoff              0
total_monthly_runoff    9422
flood_magnitude            0
dtype: int64

In [10]:
df['flood_event_runoff']= df['flood_event_runoff'].fillna(0)

In [11]:
df.isnull().sum()

date                       0
daily_avg_discharge        0
flood_event_runoff         0
daily_runoff               0
weekly_runoff              0
total_monthly_runoff    9422
flood_magnitude            0
dtype: int64

In [12]:
df=df.drop(columns=['total_monthly_runoff'],axis=1)

In [13]:
df.isnull().sum()

date                   0
daily_avg_discharge    0
flood_event_runoff     0
daily_runoff           0
weekly_runoff          0
flood_magnitude        0
dtype: int64

In [14]:
df.to_csv('flood4.csv')

In [15]:
df=df.set_index(['date'],drop=['date'])

In [16]:
X= df.drop(columns=['flood_magnitude'],axis=1)

In [17]:
y=df['flood_magnitude']

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [20]:
from sklearn.svm import SVR

In [21]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [22]:
scaler=StandardScaler()

In [23]:
scaled_X_train=scaler.fit_transform(X_train)

In [24]:
scaled_X_test=scaler.transform(X_test)

In [25]:
model= SVR()

In [26]:
param_grid ={
    'C':[0.001,0.003,0.01,0.02,0.08,0.1,0.3,0.5,0.55],
    'kernel':['linera','rbf','poly'],
    'gamma':['scale','auto'],
    'degree':[2,3,4,5,6,7,8],
    'epsilon':[0,0.01,0.1,0.3,0.5,1]
}

In [27]:
from sklearn.model_selection import GridSearchCV

In [28]:
grid=GridSearchCV(model,param_grid,verbose=1)

In [ ]:
grid.fit(scaled_X_train,y_train)

Fitting 5 folds for each of 2268 candidates, totalling 11340 fits

In [ ]:
grid.best_params_

In [ ]:
grid_preds=grid.predict(scaled_X_test)

In [ ]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [ ]:
mean_squared_error(y_test,grid_preds)